export default defineEventHandler(() => {
  return [
    {
      id: 1,
      name: 'Сlavia Nord Grand сценическое цифровое пианино',
      price: 450500,
      prefix: false,
      image: '/assets/images/product1.png',
      views: 750,
      shows: 2,
      status: true,
      move: true,
    },
    {
      id: 2,
      name: 'Hyundai Sonata 2.0 AT, 2023, 30 км',
      price: 3285000,
      prefix: false,
      image: '/assets/images/product2.png',
      views: 255,
      shows: 4,
      status: true,
      move: false,
    },
    {
      id: 3,
      name: '2-к. квартира, 46 м², 1/5 эт.',
      price: 4800000,
      prefix: false,
      image: '/assets/images/product3.png',
      views: 255,
      shows: 4,
      status: true,
      move: false,
    },
    {
      id: 4,
      name: 'Старые барабаны',
      price: 7500,
      prefix: 'шт',
      image: '/assets/images/product4.png',
      views: 255,
      shows: 2,
      status: true,
      move: false,
    },
    {
      id: 5,
      name: 'DMX сплиттер RJ45 to 4x XLR Stairville',
      price: 7500,
      prefix: false,
      image: '/assets/images/product5.png',
      views: 255,
      shows: 2,
      status: true,
      move: false,
    },
    {
      id: 6,
      name: 'Мотоцикл honda',
      price: 217500,
      prefix: false,
      image: '/assets/images/product6.png',
      views: 255,
      shows: 2,
      status: true,
      move: false,
    },
    {
      id: 7,
      name: 'Иж юпитер 5',
      price: 17900,
      prefix: false,
      image: '/assets/images/product7.png',
      views: 255,
      shows: 2,
      status: true,
      move: false,
    },
    {
      id: 8,
      name: 'Пылесос кёрхер с водяным мешком для сбора пыли',
      price: 7500,
      prefix: false,
      image: '/assets/images/product8.png',
      views: 255,
      shows: 2,
      status: false,
      move: false,
    },
  ]
})
